### ISSUE TITLE
gcp-service-broker not compatible with k8s 1.16

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/addons#134]
**Description**
The gcp-service-broker with the "default" plan is using a bundled mysql. The sub-chart provided as zip file is based on the outdated Deployment apiGroup and with that a deployment fails on k8s 1.16.

Please update the chart to the latest apiGroup.
I think inflating the zip file in the source code will also be beneficial as a search for outdated terms will have matches.

**Expected result**

**Actual result**

**Steps to reproduce**
Instantiate the broker with the "default" plan on kyma.10 with k8s 1.16 underneath

**Troubleshooting**

**Comment by mszostok** [comment]
check also why icon is missing:
![image](https://user-images.githubusercontent.com/17568639/76071185-20e78b80-5f96-11ea-90b6-f76e89e95493.png)

**Comment by polskikiel** [comment]
I couldn't test it e2e on kyma console due to this issue: https://github.com/kyma-project/console/issues/1626
