### ISSUE TITLE
Create preview addon for GoogleCloudPlatform/gcp-service-broker

### ISSUE THREAD

**Issue by PK85** [kyma-project/addons#94]
**Description**

Provide a new GCP Service Broker installation at runtime. Old one was deprecated by google.

**Reasons**

Allow Kyma users to integrate GCP Service Broker with Kyma in an easy way with well documented steps described in a documentation of the service class.

**Acceptance Criteria**
- make an addon for GCP Service Broker
  - keep all naming conventions, like description etc synced with already existing Azure and AWS addons
  - check if addon requires some input parameters (for example Azure Broker has such one)
  - addon itself implementation and doc
- create service class documentation for above addon
  - add documentation per every GCP class, use reference to GCP documentation if available
- make sure all input parameters are displayed correctly in Service Catalog UI
- release addons repository and use new version in Kyma
- keep addon GCP image/chart version and docs with the same version
- change addon id (name must stay). I mean do not use previous one.
- install broker in kyma, delete and install should nicely work
- if seceret not provided, should fail asap

**Attachments**
- Documentation, see: https://github.com/GoogleCloudPlatform/gcp-service-broker
- Installation on Kubernetes, see: https://github.com/GoogleCloudPlatform/gcp-service-broker/tree/develop/deployments/helm/gcp-service-broker

**Comment by mszostok** [comment]
If we will need to add some tool to provision that new broker, then contact Andreas Thaler where (in which directory) to put that tool.

**Comment by piotrmiskiewicz** [comment]
The gcp-broker is not ready to deploy to Kubernetes, I've created an issue in the gcp-broker project:
https://github.com/GoogleCloudPlatform/gcp-service-broker/issues/486

**Comment by PK85** [comment]
Timeb-boxed to 13SP.

**Comment by adamwalach** [comment]
PR to upstream to fix the build process:
https://github.com/GoogleCloudPlatform/gcp-service-broker/pull/488

**Comment by adamwalach** [comment]
Fixes to forked repo: https://github.com/kyma-incubator/gcp-service-broker/pull/1
